### ISSUE TITLE
Dave, my faster replacement is giving different answers, I'm afraid, Dave ...

### ISSUE THREAD

**Issue by jlstiles** [jeremyrcoyle/hal9001#9]
```
devtools::install_github("jlstiles/Simulations")
library(hal9001)
library(Simulations)

# using built-in functions in Simulations pack
n = 200
data  = gendata(n, g0=g0_linear,Q0=Q0_trig1)
X = data
X$Y = NULL
Y = data$Y
X0 = X1 = X
X0$A = 0
X1$A = 1
newdata = rbind(X, X1, X0)

time = proc.time()
halres <- hal(Y = Y, newX = newdata, X = X, family = binomial(), 
                                   verbose = FALSE, parallel = FALSE)
timehal = proc.time() - time

Qk = halres$pred[1:n]
Q1k = halres$pred[n+1:n]
Q0k = halres$pred[2*n+1:n]

# estimating blip var and ATE
esthal = var(Q1k-Q0k)
esthalATE = mean(Q1k-Q0k)

time = proc.time()
halres9001 <- fit_hal(Y = Y, X = X)
timehal9001 = proc.time() - time

Qk = predict(halres9001, new_data = newdata)[1:n]
Q1k = predict(halres9001, new_data = newdata)[n+1:n]
Q0k = predict(halres9001, new_data = newdata)[2*n+1:n]

# estmating blip var and ATE
esthal9001 = var(Q1k-Q0k)
esthal9001ATE = mean(Q1k-Q0k)

timehal
timehal9001

# answers are different, consistently hal9001 is underestimating both compared with hal
# blip variance is about 1/2 of what hal gives and ATE is considerably smaller, tried with n up
# to 500

esthal
esthal9001

esthalATE
esthal9001ATE
```

**Comment by jeremyrcoyle** [comment]
Thanks for the heads up. I'll take a look today. Any idea how they preform in terms of prediction MSE on a test set?

**Comment by nhejazi** [comment]
In case the answers differ by only small amounts, it's worth noting that `hal::hal` calls `cv.glmnet` with the following special arguments:
```r
cv.glmnet(..., lambda.min.ratio = 0.001, type.measure = "deviance",
                nfolds = ifelse(length(Y) <= 100, 20, 10), family = "gaussian", alpha = 1,
                nlambda = 100)
```
while by comparison, `hal9001::fit_hal` calls `cv.glmnet` as follows:
```r
# note that x_basis is created internally by HAL9001
cv.glmnet(x = x_basis, y = y, ...)
```
thus, to get the same performance, at a minimum the extra hard-coded arguments to `cv.glmnet` from `hal::hal` should be passed directly to `cv.glmnet` through `hal9001::fit_hal` via the `...` argument.

**Comment by jeremyrcoyle** [comment]
After some investigation, i've found a few discrepancies that could explain different predictions

- As pointed out here: https://github.com/jeremyrcoyle/hal9001/issues/9#issuecomment-327845383, `cv.glmnet` is being invoked with different arguments
- `cv.glmnet` randomly generates cv folds, and so will not give the same results even with two sequential calls with the same arguments (unless `set.seed` is called first, or `foldids` is specified).
- `hal::hal` fails to correctly identify duplicates. This can be seen by comparing `halres$dupInds` (used to determine if the basis function needs to be subset) and `halres$colDups` (correctly identifies duplicates). This could be fixed if https://github.com/benkeser/halplus/blob/master/R/hal.R#L136 was changed from `datDT[, duplicates := duplicated(datDT)]` to `datDT[, `:=`(duplicates, duplicated(datDT$bit_to_int_to_str))]`

Because of these differences, it's hard to conclude much from differences in prediction. It might be worth quickly fixing the bug in `hal::hal` so that it's easier to verify that the versions produce similar predictions. Thoughts @benkser, @osofr?

**Comment by benkeser** [comment]
Gosh, I get a headache just looking at that code even briefly. My bet is the issue is stemming from one or both of the first two points. I'm betting that even though (apparently) `dupInds` is wrong, it's length is almost always > 0, so I think that `if` statement will almost always evaluate to `TRUE` (at which point `colDups` is used to [apparently correctly] get rid of duplicate columns).

**Comment by jeremyrcoyle** [comment]
At least in this example it's length is 0. Here's a cleaner test to illustrate that: https://github.com/jeremyrcoyle/hal9001/blob/811e1acfe8747f88f5312eda1edce5b4ff80fc95/tests/testthat/test_stat_performance.R

**Comment by jeremyrcoyle** [comment]
In fact, as best I can tell, it will always be length 0, because it's checking for duplicates in a data.table with a unique id column (generated here: https://github.com/benkeser/halplus/blob/master/R/hal.R#L97)

**Comment by benkeser** [comment]
Well that's not good...

**Comment by osofr** [comment]
Please try it now, this commit hopefully fixes it: https://github.com/benkeser/halplus/commit/abb5a9253c951518bb8273e94b834eee45bf6d39

The bug is due to a syntax change in data.table S3 function "duplicated"

**Comment by benkeser** [comment]
Clearly the `data.table` people didn't check our downstream dependencies. How rude and inconvenient to our 4 users!

**Comment by nhejazi** [comment]
Resolved as part of https://github.com/jeremyrcoyle/hal9001/pull/24
